### ISSUE TITLE
Install, step 6: Cant find files in /etc/default/actinia

### ISSUE THREAD

**Issue by ahalota** [mundialis/actinia_core#172]
I'm following the install instructions here : https://actinia.mundialis.de/tutorial/installation.html 

My OS is Linux Mint 20.1, v4.8.6 . The computer has not been used for much before so it is empty of most additional libraries not explicitly mentioned in the installation instructions.

Step 6 says:

> Make sure that a redis service is running

I don't know what that is so I'll look it up. I would recommend turning this into a link to instructions for starting a redis service. I am now following these instructions: https://redis.io/topics/quickstart . Fairly easy to follow so that worked, and I turned it on.
From here, the instructions state:
```
cd /tmp
source actinia_venv/bin/activate

# Create the superuser
actinia-user create -u superadmin -w abcdefgh -r superadmin -g admin -c 100000000000 -n 1000 -t 6000

# Start the actinia service with
actinia_server --host 0.0.0.0 --port 5000
```

When I try to run actinia-user create, I get an error
```
Traceback (most recent call last):
  File "/home/halota/actinia/workspace/tmp/actinia_venv/bin/actinia-user", line 4, in <module>
    __import__('pkg_resources').run_script('actinia-core==0.99.26.post0.dev1+ge1510fc', 'actinia-user')
  File "/home/halota/actinia/workspace/tmp/actinia_venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/halota/actinia/workspace/tmp/actinia_venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1462, in run_script
    exec(code, namespace, namespace)
  File "/home/halota/actinia/workspace/tmp/actinia_venv/lib/python3.8/site-packages/actinia_core-0.99.26.post0.dev1+ge1510fc-py3.8.egg/EGG-INFO/scripts/actinia-user", line 30, in <module>
    from actinia_core.resources.common.user import ActiniaUser
  File "/home/halota/actinia/workspace/tmp/actinia_venv/lib/python3.8/site-packages/actinia_core-0.99.26.post0.dev1+ge1510fc-py3.8.egg/actinia_core/resources/common/user.py", line 35, in <module>
    from actinia_core.resources.common.redis_user import redis_user_interface
  File "/home/halota/actinia/workspace/tmp/actinia_venv/lib/python3.8/site-packages/actinia_core-0.99.26.post0.dev1+ge1510fc-py3.8.egg/actinia_core/resources/common/redis_user.py", line 28, in <module>
    from .redis_base import RedisBaseInterface
  File "/home/halota/actinia/workspace/tmp/actinia_venv/lib/python3.8/site-packages/actinia_core-0.99.26.post0.dev1+ge1510fc-py3.8.egg/actinia_core/resources/common/redis_base.py", line 29, in <module>
    from .logging_interface import log
  File "/home/halota/actinia/workspace/tmp/actinia_venv/lib/python3.8/site-packages/actinia_core-0.99.26.post0.dev1+ge1510fc-py3.8.egg/actinia_core/resources/common/logging_interface.py", line 40, in <module>
    global_config.read()
  File "/home/halota/actinia/workspace/tmp/actinia_venv/lib/python3.8/site-packages/actinia_core-0.99.26.post0.dev1+ge1510fc-py3.8.egg/actinia_core/resources/common/config.py", line 334, in read
    with open(path, 'r') as configfile:
FileNotFoundError: [Errno 2] No such file or directory: '/etc/default/actinia'
```

Not sure if this is related to some install location being different than expected, or if I missed some step. I do not have any actinia folder in /etc/default.

**Comment by ahalota** [comment]
I solved this issue by running
`touch /etc/default/actinia` .

**Comment by ahalota** [comment]
Next error on trying to run this:
```
    from colorlog import ColoredFormatter
ModuleNotFoundError: No module named 'colorlog'
```

Easy fix in adding `colorlog` to requirements.txt or requirements_ubuntu19.txt I don't see it in either right now and am unclear which is the "live" requirements file, can someone suggest where to add it to?

**Comment by ahalota** [comment]
Last simple fix:
`actinia_server --host 0.0.0.0 --port 5000`
Should read:
`actinia-server --host 0.0.0.0 --port 5000`
