### ISSUE TITLE
pystac import error

### ISSUE THREAD

**Issue by mmacata** [mundialis/actinia_core#332]
For current actinia_core main branch, actinia is not able to startup. Can be reproduced by following the [steps for local dev setup](https://github.com/mundialis/actinia_core/tree/main/docker#local-dev-setup-with-docker):
```
docker-compose -f docker-compose-dev.yml build
docker-compose -f docker-compose-dev.yml run --rm --service-ports --entrypoint sh actinia

# Then, inside the docker container, run
python3 setup.py install
sh /src/start.sh
```

Error is:
```
[2022-03-25 15:51:30,372] INFO      : actinia-core.logging_interface -Log level is set to 'INFO' [in /src/actinia_core/src/actinia_core/core/logging_interface.py:246]
[2022-03-25 15:51:31,997] INFO      : actinia-core.logging_interface -Log level is set to 'INFO' [in /src/actinia_core/src/actinia_core/core/logging_interface.py:246]
[2022-03-25 15:51:35,232] INFO      : werkzeug._internal  -172.18.0.1 - - [25/Mar/2022 15:51:35] "GET /api/v3/version HTTP/1.1" 500 - [in /usr/lib/python3.8/site-packages/werkzeug/_internal.py:113]
[2022-03-25 15:51:35,239] ERROR     : werkzeug._internal  -Error on request:
Traceback (most recent call last):
  File "/src/actinia_core/src/actinia_core/main.py", line 30, in <module>
    from .endpoints import create_endpoints
  File "/src/actinia_core/src/actinia_core/endpoints.py", line 50, in <module>
    from actinia_core.rest.ephemeral_processing_with_export import \
  File "/src/actinia_core/src/actinia_core/rest/ephemeral_processing_with_export.py", line 42, in <module>
    from actinia_core.core.stac_exporter_interface import STACExporter
  File "/src/actinia_core/src/actinia_core/core/stac_exporter_interface.py", line 40, in <module>
    from pystac.extensions.projection import ProjectionItemExt
ImportError: cannot import name 'ProjectionItemExt' from 'pystac.extensions.projection' (/usr/lib/python3.8/site-packages/pystac/extensions/projection.py)
```

**Comment by mmacata** [comment]
Sorry, I was happy too soon: the error still exists, even after the merge. Locally I outcommented the broken imports https://github.com/mundialis/actinia_core/blob/main/src/actinia_core/core/stac_exporter_interface.py#L39-L40 so they don't block me. I forgot to incomment them again when testing #333. @joaherrerama could you have one more look at this please?

**Comment by joaherrerama** [comment]
I took a look, but I could not reproduce the error, with the steps described above, is there any other step?
